server.port: 8888
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lottery
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org:
      springframework:
        security: DEBUG